# Generated by Django 4.0.6 on 2022-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
